# Generated by Django 4.0.6 on 2022-10-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('worker', 'Работник'), ('client', 'Клиент')], default='client', max_length=6, verbose_name='Тип'),
        ),
    ]
